### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by pjrobin** [THSoftPoland/DelphiMessageBus#2]
May I ask you to provide an example how tu use MessageBus with multithreading? Thanks!

**Comment by THSoftPoland** [comment]
Thread1 - data source (sender) :

aStr := TStringList.Create;
aStr.Add('Demo');
try
  TMessageBus.Default.Send<TStringList>(commonKey, aStr);
finally
  aStr.Free;
end;

Subscribers (receivers)

Thread2:

myCopy: TStringList;
TMessageBus.Default.Subscribe<TStringList>(commonKey,
  procedure(const aValue: TStringList; aEnv: TMessageBus..TBusEnvir)
  begin
    myCopy := TStringList.Create;
    aEnv.Lock;
	try
	  myCopy.Text := aValue.Text;
	finally
	  aEnv.Unlock;
	end;
  end);
  
  
MainThread (VCL)

myCopy: TStringList;
TMessageBus.Default.Subscribe<TStringList>(commonKey,
  procedure(const aValue: TStringList; aEnv: TMessageBus..TBusEnvir)
  begin
    myCopy := TStringList.Create;
    aEnv.Lock;
    try
       myCopy.Text := aValue.Text;
       PostMessage(self.Handle, WM_USER, 0, 0);  // PING to Form
     finally
       aEnv.Unlock;
     end;
  end);
